require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ToDosController do

  # This should return the minimal set of attributes required to create a valid
  # ToDo. As you add validations to ToDo, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all to_dos as @to_dos" do
      to_do = ToDo.create! valid_attributes
      get :index
      assigns(:to_dos).should eq([to_do])
    end
  end

  describe "GET show" do
    it "assigns the requested to_do as @to_do" do
      to_do = ToDo.create! valid_attributes
      get :show, :id => to_do.id
      assigns(:to_do).should eq(to_do)
    end
  end

  describe "GET new" do
    it "assigns a new to_do as @to_do" do
      get :new
      assigns(:to_do).should be_a_new(ToDo)
    end
  end

  describe "GET edit" do
    it "assigns the requested to_do as @to_do" do
      to_do = ToDo.create! valid_attributes
      get :edit, :id => to_do.id
      assigns(:to_do).should eq(to_do)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ToDo" do
        expect {
          post :create, :to_do => valid_attributes
        }.to change(ToDo, :count).by(1)
      end

      it "assigns a newly created to_do as @to_do" do
        post :create, :to_do => valid_attributes
        assigns(:to_do).should be_a(ToDo)
        assigns(:to_do).should be_persisted
      end

      it "redirects to the created to_do" do
        post :create, :to_do => valid_attributes
        response.should redirect_to(ToDo.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved to_do as @to_do" do
        # Trigger the behavior that occurs when invalid params are submitted
        ToDo.any_instance.stub(:save).and_return(false)
        post :create, :to_do => {}
        assigns(:to_do).should be_a_new(ToDo)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ToDo.any_instance.stub(:save).and_return(false)
        post :create, :to_do => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested to_do" do
        to_do = ToDo.create! valid_attributes
        # Assuming there are no other to_dos in the database, this
        # specifies that the ToDo created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ToDo.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => to_do.id, :to_do => {'these' => 'params'}
      end

      it "assigns the requested to_do as @to_do" do
        to_do = ToDo.create! valid_attributes
        put :update, :id => to_do.id, :to_do => valid_attributes
        assigns(:to_do).should eq(to_do)
      end

      it "redirects to the to_do" do
        to_do = ToDo.create! valid_attributes
        put :update, :id => to_do.id, :to_do => valid_attributes
        response.should redirect_to(to_do)
      end
    end

    describe "with invalid params" do
      it "assigns the to_do as @to_do" do
        to_do = ToDo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ToDo.any_instance.stub(:save).and_return(false)
        put :update, :id => to_do.id, :to_do => {}
        assigns(:to_do).should eq(to_do)
      end

      it "re-renders the 'edit' template" do
        to_do = ToDo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ToDo.any_instance.stub(:save).and_return(false)
        put :update, :id => to_do.id, :to_do => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested to_do" do
      to_do = ToDo.create! valid_attributes
      expect {
        delete :destroy, :id => to_do.id
      }.to change(ToDo, :count).by(-1)
    end

    it "redirects to the to_dos list" do
      to_do = ToDo.create! valid_attributes
      delete :destroy, :id => to_do.id
      response.should redirect_to(to_dos_url)
    end
  end

end
